### ISSUE TITLE
Not good securty

### ISSUE THREAD

**Issue by eggbeard** [brainwipe/DockerDotNetOAuth#1]
Nice to see a working example hosted in Docker, but holding the secret in you client js and posting to the token server is not good practice.  You probably want an Implicit Flow for this

**Comment by brainwipe** [comment]
Thanks for the feedback. I agree that it's not ideal. 

However, I put this example together because there were lots of examples of implicit flow but none that used a username/password client. In some cases, you're able to redirect but for the purposes of this example, I am not able to. The client here is a bit of javascript but could easily be a command line app or a 3rd party.

Don't forget that the token is included in the headers on each AJAX call anyway, so you're not gaining much benefit from implicit here.

**Comment by eggbeard** [comment]
The problem is not the token.  The problem is exposing the the secret, which you are handing out to everyone who cares to do a view source on the js code.

But you are correct if the client were a Node server application for example, then this would be fine.
